name: icon_craft
description: "IconCraft allows developers to create richer iconography with the ability to combine two icons into a single widget"
version: 0.1.1
homepage: https://github.com/vicenterusso/icon_craft
repository: https://github.com/vicenterusso/icon_craft
issue_tracker: https://github.com/vicenterusso/icon_craft/issues


environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

topics:
  - icon
  - ui
  - design